name: Javadocs Build for Site

on:
  push:
    tags: 
        - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 'openjdk11']
      fail-fast: false
    steps:
    - name: Gets the version
      id: get_version
      run: echo ::set-env name=TAG_VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Setup GraphViz environment for PlanetUML/JavaDoc Graphics
      uses: kamiazya/setup-graphviz@v1
    - name: Grab the Master Branch
      uses: actions/checkout@v2
      with:
            ref: refs/heads/master
            fetch-depth: 1
            path: fhir
            token: ${{ secrets.DOCS_SITE_TOKEN }}
    - name: Grab the GH-Pages Branch
      uses: actions/checkout@v2
      with:
            ref: refs/heads/gh-pages
            fetch-depth: 1
            path: gh-pages
            token: ${{ secrets.DOCS_SITE_TOKEN }}
    - name: Set up OpenJDK
      uses: joschi/setup-jdk@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build fhir-samples
      run: |
            cd fhir
            mvn -B -ntp clean install --file fhir-examples -Ddeploy.version=${TAG_VERSION}
            mvn -ntp -B -N -Pdeploy-version-release clean -f fhir-examples -Ddeploy.version=${TAG_VERSION}
            mvn -ntp -B install --file fhir-examples -DskipTests -Ddeploy.version=${TAG_VERSION}
    - name: Build fhir-parent without tests
      run: |
            cd fhir
            export JAVA_HOME=/opt/hostedtoolcache/AdoptOpenJDK/1.0.0-releases-${{ matrix.java }}-hotspot-normal-latest/x64/
            mvn -ntp -B -N -Pdeploy-version-release clean -f fhir-parent -Ddeploy.version=${TAG_VERSION} -Dfhir-tools.version=${TAG_VERSION}
            mvn -ntp -B install --file fhir-parent -DskipTests -Ddeploy.version=${TAG_VERSION} -Dfhir-tools.version=${TAG_VERSION}
            mvn -ntp -B site --file fhir-parent -DskipTests -Ddeploy.version=${TAG_VERSION} -Dfhir-tools.version=${TAG_VERSION}
            cp -R fhir-parent/target/site/apidocs ../apidocs/
    - name: Commit and Add GH-Pages
      env:
            GITHUB_TOKEN: ${{ secrets.DOCS_SITE_TOKEN }}
            GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
            GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
            CI: true
      run: |
            cd gh-pages
            echo "Working Directory is $(pwd)"
            if [ -d './javadocs/latest/' ]
            then
              rm -rf ./javadocs/latest/
            fi
            # Helps debug the situation 
            ls -al javadocs
            echo "Starting the movement of the data around"
            mkdir -p javadocs/latest
            mv -f ../apidocs/* javadocs/latest/
            cp -Rf javadocs/latest javadocs/${TAG_VERSION}
            date > build.txt
            echo "[javadocs]" >> build.txt

            # Regenerate the index.html for javadocs/index.html
            echo "<html><title>Javadocs</title><body>" > javadocs/index.html
            for DIR in `find ./javadocs -type d -maxdepth 1 -mindepth 1 -exec basename {} \; | sort -r | grep -v rc3 `
            do
              echo "<a href=\"https://ibm.github.io/FHIR/javadocs/${DIR}/index.html?overview-summary.html\">${DIR}</a>" >> javadocs/index.html 
              echo "<br>" >> javadocs/index.html
            done
            echo "</body></html>" >> javadocs/index.html

            git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            git config --global user.name "Github Actions Bot - GH-Pages"
            git add .
            git commit -m "Automated gh-pages deployment of javadocs: $(date -u)"
    - name: Push changes to GH Pages
      env:
            GITHUB_TOKEN: ${{ secrets.DOCS_SITE_TOKEN }}
            GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
            GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
            CI: true
      run: |
            echo "Pushing Changes to gh-pages"
            cd gh-pages
            git branch
            remote_repo="https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
            git push "${remote_repo}" HEAD:gh-pages
    - name: Request GitHub Pages Build
      env:
            GITHUB_TOKEN: ${{ secrets.DOCS_SITE_TOKEN }}
            GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
            GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
      run: |
            # As documented here, the GH-Pages behavior changed, and the API must be 'Triggered'
            # https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/m-p/43192/highlight/true#M5281
            curl -L -X POST -H "Content-Type: application/json" -H "Authorization: token ${GITHUB_TOKEN}" "https://api.github.com/repos/${GITHUB_REPOSITORY}/pages/builds"
